# Makefile for all of lab_02

# targets
OBJ1 = lab_02_01_01.cpp
OBJ2 = lab_02_01_02.cpp
OBJ3 = lab_02_02.cpp
OBJ4 = lab_02_03.cpp

# executables
EXEC1 = lab_02_01_01
EXEC2 = lab_02_01_02
EXEC3 = lab_02_02
EXEC4 = lab_02_03

# compiler
CC = g++

make:
	$(CC) -o $(EXEC1) $(OBJ1)
	$(CC) -o $(EXEC2) $(OBJ2)
	$(CC) -o $(EXEC3) $(OBJ3)
	$(CC) -o $(EXEC4) $(OBJ4)