# Makefile for birthday_notifications.c

# Source Files
OBJS = birthday_notifications.c

# Executable
EXEC = birthday_notifications

# Compiler
CC = gcc

make: $(OBJS)
	$(CC) -o $(EXEC) $(OBJS) 

run: $(EXEC)
	./$(EXEC)