# Makefile for all of lab_03

# targets
OBJ1 = lab_03_01.cpp
OBJ2 = lab_03_02.cpp
OBJ2 = lab_03_03.cpp

# executable
EXEC1 = lab_03_01
EXEC2 = lab_03_02
EXEC3 = lab_03_03

# compiler
CC = g++

make:
	$(CC) -o $(EXEC1) $(OBJ1)
	$(CC) -o $(EXEC2) $(OBJ2)
	$(CC) -o $(EXEC3) $(OBJ3)